org: shimonosatoru
app: subscription-register
service:
  name: subscriptions-register-server

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1

functions:
  createCustomer:
    handler: handler.createCustomer
    events:
      - http:
          method: post
          path: create-customer
          cors: true
